name: PR

on:
  workflow_call:
    secrets:
      pact_broker_username:
        required: true
      pact_broker_password:
        required: true
      PERCY_TOKEN:
        required: true 

permissions:
  contents: read

jobs:
  install-and-compile:
    name: "Install and compile"
    uses: alphagov/pay-ci/.github/workflows/_run-node-install-and-compile.yml@master
    with:
      has_cypress_tests: true

  tests:
    name: "Unit tests and pacts"
    needs: [ install-and-compile ]
    uses: alphagov/pay-ci/.github/workflows/_run-node-unit-tests-and-publish-pacts.yml@master
    with:
      publish_pacts: true
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  cypress-tests:
    name: "Cypress"
    needs: [ install-and-compile ]
    uses: alphagov/pay-ci/.github/workflows/_run-node-cypress-tests.yml@pp-12795-percy
    with:
      LIBGL_ALWAYS_SOFTWARE: "1"
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  pact-providers-contract-tests:
    name: "Provider tests"
    needs: tests
    uses: alphagov/pay-ci/.github/workflows/_run-provider-pact-tests-for-consumer.yml@master
    strategy:
      matrix:
        provider: [ 'adminusers', 'connector', 'ledger', 'products' ]
    with:
      consumer: "selfservice"
      provider: ${{ matrix.provider }}
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  check-docker-base-images-are-manifests:
    uses: alphagov/pay-ci/.github/workflows/_validate_docker_image_is_manifest.yml@master
