name: PR

on:
  workflow_call:
    secrets:
      PERCY_TOKEN:
        required: true 

permissions:
  contents: read

jobs:
  install-and-compile:
    name: "Install and compile"
    uses: alphagov/pay-ci/.github/workflows/_run-node-install-and-compile.yml@master
    with:
      has_cypress_tests: true

  cypress-tests:
    name: "Cypress"
    needs: [ install-and-compile ]
    uses: alphagov/pay-ci/.github/workflows/_run-node-cypress-tests.yml@pp-12795-percy
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
